---
- name: apply updates - windows
  hosts: "{{ node_name }}"
  become: true
  gather_facts: false
  vars:
    group_name: trickyusers
    user_IDs:
      - user1
      - user2
      - user3

  tasks:
  - name: User group {{ group_name }} exists
    group:
      name: "{{ group_name }}"
      state: present

  - name: Add users to group {{ group_name }}
    user: name={{ item }} group={{ group_name }} comment='created with developer-self-provision playbook'
    with_items: " {{user_IDs}} "

  - name: Put in Ansible inventory group {{ machine_type }}
    add_host:
      name: " {{ node_name }} "
      groups: " {{ machine_type }} "
